# Generated by Django 3.0.7 on 2020-06-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='Mensalista',
            new_name='mensalista',
        ),
    ]
